AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation template to create serverless ETL data upsert solution
Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "ETLTest"
      Role: 'arn:aws:iam::345814638087:role/IAM-GLUE-SERVICE'
      Command:
        Name: glueetl
        PythonVersion:  '3'
        ScriptLocation:
          Fn::Sub:  's3://s3-ftp-source/code/code.py'
      GlueVersion:  '2.0'
      WorkerType: 'Standard'
      NumberOfWorkers:  2
      ExecutionProperty:
        MaxConcurrentRuns:  24
  Type: 'AWS::Lambda::LayerVersion'
  Properties:
    CompatibleRuntimes:
      - 'python3.9'
    Content:
      S3Bucket: 's3-my-softwares'
      S3Key: 'package/python.zip'
      Description:  'Python package'
      LayerName:  'pagla'