AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation template to create serverless ETL data upsert solution
Parameters:
  pPyPackageBucket:
    Type: String
    Description: S3 Bucket for software lib package
  
Resources:
  LambdaLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      CompatibleRuntimes:
        - 'python3.9'
      Content:
        S3Bucket:
          Ref: pPyPackageBucket
        S3Key: 'package/python.zip'
      Description:  'Python package'
      LayerName:  'hghnfgh'