AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation template to create serverless ETL data upsert solution
Parameters:
  pEnv:
    Type: String
    Description: AWS environment
  pRawIngestLambda:
    Type: String
    Description: Data generator lambda function name
  pPyPackageBucket:
    Type: String
    Description: S3 Bucket for software lib package
  pPyPackageKey:
    Type: String
    Description: S3 Key for software lib package
  pPyPackagePandas:
    Type: String
    Description: Python lib name
Resources:
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: "ETLTest"
      Role: 'arn:aws:iam::345814638087:role/IAM-GLUE-SERVICE'
      Command:
        Name: glueetl
        PythonVersion:  '3'
        ScriptLocation:
          Fn::Sub:  's3://s3-ftp-source/code/code.py'
      GlueVersion:  '2.0'
      WorkerType: 'Standard'
      NumberOfWorkers:  2
      ExecutionProperty:
        MaxConcurrentRuns:  24
  LambdaLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      CompatibleRuntimes:
        - 'python3.9'
      Content:
        S3Bucket: !Ref ${pPyPackageBucket}
        S3Key: !Ref ${pPyPackageKey}/${pPyPackagePandas}
      Description:  'Python package'
      LayerName:  'pagla'