AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation template to create serverless ETL data upsert solution
Parameters:
  pPyPackageBucket:
    Type: String
    Description: S3 Bucket for software lib package
  pPyPackageKey:
    Type: String
    Description: Library path
  pPyPackagePandas:
    Type: String
    Description: Package name
  pllypharmaLambdaScripts:
    Type: String
    Description: Lambda script location
  pLambdaDataGenerator:
    Type: String
    Description: Data generator code
Resources:
  LambdaLayer:
    Type: 'AWS::Lambda::LayerVersion'
    Properties:
      CompatibleArchitectures:
        - 'x86_64'
      CompatibleRuntimes:
        - 'python3.9'
      Content:
        S3Bucket: !Ref pPyPackageBucket
        S3Key: !Sub ${pPyPackageKey}/${pPyPackagePandas}
      Description:  'Python package'
      LayerName:  'pandas'
  LLLYPHARMADATAGEN:
    Type: AWS::Lambda::Function
    Properties:
      Runtime: python3.9
      Role: arn:aws:iam::345814638087:role/IAM-LAMBDA-SERVICE
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: !Ref pPyPackageBucket
        S3Key: !Sub ${pllypharmaLambdaScripts}/${pLambdaDataGenerator}
      Timeout: 300
      MemorySize: 3008
      Description: Generate data
