AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CloudFormation template to create serverless ETL data upsert solution
Resources:
  Type: 'AWS::Lambda::LayerVersion'
  Properties:
    CompatibleRuntimes:
      - 'python3.9'
    Content:
      S3Bucket: !Sub '${pPyPackageBucket}'
      S3Key: !Sub '${pPyPackageKey}/${pPyPackagePandas}'
      Description:  'Python package'
      LayerName:  'pandas'